In [1]:
import networkx as nx # Networkx Library
import numpy as np #Numpy library
import matplotlib.pyplot as plt

In [2]:
# Trivial REL Graph example

#Matrix initialisation
matrix = np.zeros((5,5),int)
matrix[0][1] = 2
matrix[0][2] = 3
matrix[1][2] = 1
matrix[1][4] = 1
matrix[2][1] = 1
matrix[2][3] = 1
matrix[3][0] = 2
matrix[3][2] = 1
matrix[3][4] = 1
matrix[4][0] = 3
matrix[4][1] = 1
matrix[4][3] = 1

print(matrix)

def find_ordered_neighbours (matrix, vertex):
    #find non-zero elements in a row
    non_zero_values = np.nonzero(matrix)
    row_non_zero=[]
    for i in np.where(non_zero_values[0] == vertex)[0]:
        row_non_zero.append(non_zero_values[1][i])


    #find non-zero elements in a column
    column_non_zero= []
    for i in np.where(non_zero_values[1] == vertex)[0]:
        column_non_zero.append(non_zero_values[0][i])

    #List for Sets T1 and T2
    t1_leaving = []
    t2_leaving = []
    t1_entering = []
    t2_entering =[]

    #Populating T1 and T2
    for i in row_non_zero:
        if matrix[vertex][i] == 2:
            t1_leaving.append(i)
        elif matrix[vertex][i] == 3:
            t2_leaving.append(i)

    for i in column_non_zero:
        if matrix[i][vertex] == 2:
            t1_entering.append(i)
        elif matrix[i][vertex] == 3:
            t2_entering.append(i)
   
    #Ordering function for vertices in given list
    def sorted_order(vertexset):
        if len(vertexset) == 1:
            return vertexset
        orderedset = []
        if len(orderedset) == 0:
            set1 = vertexset.copy()
            set1.pop(0)
            for vertices in set1:
                if matrix[vertexset[0]][vertices]!= 0 or matrix[vertices][vertexset[0]] !=0:
                    orderedset.append(vertexset[0])
                    vertexset.pop(0)
                    orderedset.append(vertices)
                    vertexset.remove(vertices)
                    break
        while len(vertexset)!=0:
            for vertices in vertexset:
                if matrix[orderedset[len(orderedset)-1]][vertices]!=0 or matrix[vertices][orderedset[len(orderedset)-1]]!=0:
                    orderedset.append(vertices)
                    vertexset.remove(vertices)
                    break
                elif matrix[orderedset[0]][vertices]!=0 or matrix[vertices][orderedset[0]]!=0:
                    orderedset.insert(0,vertices)
                    vertexset.remove(vertices)
                    break
        return orderedset      
    
    #Ordering vertices in T1 and T2
    t1_leaving = sorted_order(t1_leaving)
    t2_leaving = sorted_order(t2_leaving)
    t1_entering = sorted_order(t1_entering)
    t2_entering = sorted_order(t2_entering)

    neighbours_ordered = []
    
    #When neighbours_ordered is empty
    def counterclockwise_order_empty(set1,set2):
        def extending_neighbours_ordered(vertexset1,vertexset2):
            neighbours_ordered.extend(vertexset1)
            neighbours_ordered.extend(vertexset2)
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
        set2.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
        set1.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
        set1.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
    
    #When neighbours_ordered is non-empty
    def counterclockwise_order_nonempty(set1,set2):
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            neighbours_ordered.extend(set2)
            return neighbours_ordered
        set2.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            neighbours_ordered.extend(set2)
            return neighbours_ordered

    #Finding neighbours in order   
    neighbours_ordered = counterclockwise_order_nonempty(counterclockwise_order_nonempty(counterclockwise_order_empty(t1_leaving,t2_entering),t1_entering),t2_leaving)
    return neighbours_ordered

    
neighbours_in_order = find_ordered_neighbours(matrix,0)
print(neighbours_in_order)

[[0 2 3 0 0]
 [0 0 1 0 1]
 [0 1 0 1 0]
 [2 0 1 0 1]
 [3 1 0 1 0]]
[1, 4, 3, 2]


In [4]:
#Example 2

matrix = np.zeros((13,13),int)
matrix[0][1] = 2
matrix[2][0] = 2
matrix[0][3] = 3
matrix[4][0] = 3
matrix[0][5] = 2
matrix[6][0] = 2
matrix[0][7] = 3
matrix[8][0] = 3
matrix[9][0] = 3
matrix[10][0] = 2
matrix[0][11] = 3
matrix[0][12] = 2
matrix[1][5] = 1
matrix[5][11] = 1
matrix[11][3] = 1
matrix[3][7] = 1
matrix[7][6] = 1
matrix[6][2] = 1
matrix[2][10] = 1
matrix[10][9] = 1
matrix[9][4] = 1
matrix[4][8] = 1
matrix[8][12] = 1
matrix[12][1] = 1

print(matrix)

def find_ordered_neighbours (matrix, vertex):
    #find non-zero elements in a row
    non_zero_values = np.nonzero(matrix)
    row_non_zero=[]
    for i in np.where(non_zero_values[0] == vertex)[0]:
        row_non_zero.append(non_zero_values[1][i])


    #find non-zero elements in a column
    column_non_zero= []
    for i in np.where(non_zero_values[1] == vertex)[0]:
        column_non_zero.append(non_zero_values[0][i])

    #List for Sets T1 and T2
    t1_leaving = []
    t2_leaving = []
    t1_entering = []
    t2_entering =[]

    #Populating T1 and T2
    for i in row_non_zero:
        if matrix[vertex][i] == 2:
            t1_leaving.append(i)
        elif matrix[vertex][i] == 3:
            t2_leaving.append(i)

    for i in column_non_zero:
        if matrix[i][vertex] == 2:
            t1_entering.append(i)
        elif matrix[i][vertex] == 3:
            t2_entering.append(i)
   
    #Ordering function for vertices in given list
    def sorted_order(vertexset):
        if len(vertexset) == 1:
            return vertexset
        orderedset = []
        orderedset.append(vertexset[0])
        vertexset.pop(0)
        while len(vertexset)!=0:
            for vertices in vertexset:
                if matrix[orderedset[len(orderedset)-1]][vertices]!=0 or matrix[vertices][orderedset[len(orderedset)-1]]!=0:
                    orderedset.append(vertices)
                    vertexset.remove(vertices)
                    break
                elif matrix[orderedset[0]][vertices]!=0 or matrix[vertices][orderedset[0]]!=0:
                    orderedset.insert(0,vertices)
                    vertexset.remove(vertices)
                    break
        return orderedset      
    
    #Ordering vertices in T1 and T2
    t1_leaving = sorted_order(t1_leaving)
    t2_leaving = sorted_order(t2_leaving)
    t1_entering = sorted_order(t1_entering)
    t2_entering = sorted_order(t2_entering)

    neighbours_ordered = []
    
    #When neighbours_ordered is empty
    def counterclockwise_order_empty(set1,set2):
        def extending_neighbours_ordered(vertexset1,vertexset2):
            neighbours_ordered.extend(vertexset1)
            neighbours_ordered.extend(vertexset2)
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
        set2.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
        set1.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
        set1.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            extending_neighbours_ordered(set1,set2)
            return neighbours_ordered
    
    #When neighbours_ordered is non-empty
    def counterclockwise_order_nonempty(set1,set2):
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            neighbours_ordered.extend(set2)
            return neighbours_ordered
        set2.reverse()
        if matrix[set1[len(set1)-1]][set2[0]]!=0 or matrix[set2[0]][set1[len(set1)-1]]!=0:
            neighbours_ordered.extend(set2)
            return neighbours_ordered

    #Finding neighbours in order   
    neighbours_ordered = counterclockwise_order_nonempty(counterclockwise_order_nonempty(counterclockwise_order_empty(t1_leaving,t2_entering),t1_entering),t2_leaving)
    return neighbours_ordered

    
neighbours_in_order = find_ordered_neighbours(matrix,0)
print(neighbours_in_order)

[[0 2 0 3 0 2 0 3 0 0 0 3 2]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [2 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0 0 0 1]
 [3 0 0 0 1 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]]
[5, 1, 12, 8, 4, 9, 10, 2, 6, 7, 3, 11]
